### ISSUE TITLE
design tour page

### ISSUE THREAD

**Issue by tuanha** [tuanha/tourist#8]
![quy-issues](https://cloud.githubusercontent.com/assets/2282062/14236913/ce40b3f6-fa46-11e5-8d9e-acb0f9f70d68.png)

chỉnh form search vs btn new tour cho = với lề ngoài, show test infomation tour nếu nhiều quá thì hiện vs khoảng vài chục ký tự rồi thêm dấu ... vào phía xau là dc

**Comment by ngocquyhoang** [comment]
OK đại ca
